azure_auth_login:
  path:     /login
  controller: LouisSicard\AzureAuth\Controller\AzureAuthController::loginAction

azure_auth_logout:
  path:     /logout
  controller: LouisSicard\AzureAuth\Controller\AzureAuthController::logoutAction